SnoopShop/Models/PostTopic.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SnoopShop.Models
{
    public class PostTopic
    {
        public int PostID { get; set; }
        public string PostName { get; set; }
        public string PostImage { get; set; }
        public int PostStatus { get; set; }
        public string TopicName { get; set; }

    }
}

SnoopShop/Models/ProductCategory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SnoopShop.Models
{
    public class ProductCategory
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductImage { get; set; }
        public int ProductStatus { get; set; }
        public string CategoryName { get; set; }

    }
}

SnoopShop/Areas/Admin/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SnoopShop.Common;
using SnoopShop.Library;
using SnoopShop.Models;

namespace SnoopShop.Areas.Admin.Controllers
{
    public class ContactController : BaseController
    {
        private SnoopShopDbContext db = new SnoopShopDbContext();
        [CustomAuthorizeAttribute(RoleID = "ACCOUNTANT")]
        public ActionResult Index()
        {
            ViewBag.countTrash = db.Contact.Where(m => m.Status == 0).Count();
            return View(db.Contact.Where(m=>m.Status == 1).ToList());
        }
        [CustomAuthorizeAttribute(RoleID = "ACCOUNTANT")]
        public ActionResult Trash()
        {
            return View(db.Contact.Where(m => m.Status == 0).ToList());
        }
        [CustomAuthorizeAttribute(RoleID = "ACCOUNTANT")]
        public ActionResult Reply(int? id)
        {
            if (id == null)
            {
                Notification.set_flash("Không tồn tại liên hệ từ khách hàng!", "danger");
                return RedirectToAction("Index", "Contact");
            }
            mContact mContact = db.Contact.Find(id);
            if (mContact == null)
            {
                Notification.set_flash("Không tồn tại liên hệ từ khách hàng!", "danger");
                return RedirectToAction("Index", "Contact");
            }
            return View(mContact);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Reply(mContact mContact)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        mContact.Status = 2;
        //        mContact.Updated_at = DateTime.Now;
        //        mContact.Updated_by = 1;

        //        String content = System.IO.File.ReadAllText(Server.MapPath("~/Areas/Admin/Views/Mail/D_Mail.html"));
        //        content = content.Replace("{{FullName}}", mContact.Fullname);
        //        content = content.Replace("{{Reply}}", mContact.Reply);
        //        content = content.Replace("{{RQ}}", mContact.Detail);
        //        content = content.Replace("{{AdminName}}", Session["User_Admin"].ToString());
        //        String subject = "Phản hồi liên hệ từ Phuongnghiep.com";
        //        //new MailHelper().SendMail(mContact.Email, subject, content);

        //        db.Entry(mContact).State = EntityState.Modified;
        //        db.SaveChanges();
        //        Notification.set_flash("Đã trả lời liên hệ!", "success");
        //        return RedirectToAction("Index");
        //    }
        //    return View(mContact);
        //}
        [CustomAuthorizeAttribute(RoleID = "ACCOUNTANT")]
        public ActionResult Reply(mContact mContact)
        {
            if (ModelState.IsValid)
            {
                mContact.Flag = 1;
                mContact.Updated_at = DateTime.Now;
                mContact.Updated_by = int.Parse(Session["Admin_ID"].ToString());

                db.Entry(mContact).State = EntityState.Modified;
                db.SaveChanges();
                Notification.set_flash("Đã trả lời liên hệ!", "success");
                return RedirectToAction("Index");
            }
            return View(mContact);
        }
        [CustomAuthorizeAttribute(RoleID = "ADMIN")]
        public ActionResult DelTrash(int id)
        {
            mContact mContact = db.Contact.Find(id);
            if (mContact == null)
            {
                Notification.set_flash("Không tồn tại!", "warning");
                return RedirectToAction("Index");
            }
            mContact.Status = 0;
            mContact.Updated_at = DateTime.Now;
            mContact.Updated_by = int.Parse(Session["Admin_ID"].ToString());
            db.Entry(mContact).State = EntityState.Modified;
            db.SaveChanges();
            Notification.set_flash("Ném thành công vào thùng rác!" + " ID = " + id, "success");
            return RedirectToAction("Index");
        }
        [CustomAuthorizeAttribute(RoleID = "ADMIN")]
        public ActionResult ReTrash(int? id)
        {
            mContact mContact = db.Contact.Find(id);
            if (mContact == null)
            {
                Notification.set_flash("Không tồn tại danh mục!", "warning");
                return RedirectToAction("Trash", "Contact");
            }
            mContact.Status = 1;
            mContact.Updated_at = DateTime.Now;
            mContact.Updated_by = int.Parse(Session["Admin_ID"].ToString());
            db.Entry(mContact).State = EntityState.Modified;
            db.SaveChanges();
            Notification.set_flash("Khôi phục thành công!" + " ID = " + id, "success");
            return RedirectToAction("Trash", "Contact");
        }
        [CustomAuthorizeAttribute(RoleID = "ADMIN")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                Notification.set_flash("Không tồn tại!", "warning");
                return RedirectToAction("Index"); 
            }
            mContact mContact = db.Contact.Find(id);
            if (mContact == null)
            {
                Notification.set_flash("Không tồn tại!", "warning");
                return RedirectToAction("Index");
            }
            return View(mContact);
        }
        [CustomAuthorizeAttribute(RoleID = "ADMIN")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            mContact mContact = db.Contact.Find(id);
            db.Contact.Remove(mContact);
            db.SaveChanges();
            Notification.set_flash("Đã xóa vĩnh viễn liên hệ!", "danger");
            return RedirectToAction("Index");
        }
    }
}

SnoopShop/Areas/Admin/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SnoopShop.Common;
using SnoopShop.Models;

namespace SnoopShop.Areas.Admin.Controllers
{
    public class PostController : BaseController
    {
        private SnoopShopDbContext db = new SnoopShopDbContext();
        [CustomAuthorizeAttribute(RoleID = "ADMIN")]
        public ActionResult Index()
        {
            ViewBag.countTrash = db.Post.Where(m => m.Status == 0 && m.Type == "post").Count();
            var list = from p in db.Post
                       join t in db.Topic
                       on p.TopicID equals t.ID
                       where p.Status != 0
                       orderby p.Created_at descending
                       select new PostTopic()
                       {
                           PostID = p.ID,
                           PostImage = p.Image,
                           PostName = p.Title,
                           PostStatus = p.Status,
                           TopicName = t.Name
                       };
            return View(list.ToList());
        }
        [CustomAuthorizeAttribute(RoleID = "ADMIN")]
        public ActionResult Trash()
        {
            var list = from p in db.Post
                       join t in db.Topic
                       on p.TopicID equals t.ID
                       where p.Status == 0
                       orderby p.Created_at descending
                       select new PostTopic()
                       {
                           PostID = p.ID,
                           PostImage = p.Image,
                           PostName = p.Title,
                           PostStatus = p.Status,
                           TopicName = t.Name
                       };
            return View(list.ToList());
        }
        [CustomAuthorizeAttribute(RoleID = "ADMIN")]
        // Create
        public ActionResult Create()
        {
            mTopic mTopic = new mTopic();
            ViewBag.ListTopic = new SelectList(db.Topic.ToList(), "ID", "Name", 0);
            return View();
        }
        [CustomAuthorizeAttribute(RoleID = "ADMIN")]
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(mPost mPost)
        {
            if (ModelState.IsValid)
            {
                String strSlug = XString.ToAscii(mPost.Title);
                mPost.Slug = strSlug;
                mPost.Type = "post";
                mPost.Created_at = DateTime.Now;
                mPost.Created_by = int.Parse(Session["Admin_ID"].ToString());
                mPost.Updated_at = DateTime.Now;
                mPost.Updated_by = int.Parse(Session["Admin_ID"].ToString());
                var file = Request.Files["Image"];
                if (file != null && file.ContentLength > 0)
                {
                    String filename = strSlug + file.FileName.Substring(file.FileName.LastIndexOf("."));
                    mPost.Image = filename;
                    String Strpath = Path.Combine(Server.MapPath("~/Public/images/post/"), filename);
                    file.SaveAs(Strpath);
                }
                db.Post.Add(mPost);
                db.SaveChanges();
                Notification.set_flash("Đã thêm bài viết mới!", "success");
                return RedirectToAction("Index");
            }
            return View(mPost);
        }
        [CustomAuthorizeAttribute(RoleID = "ADMIN")]
        // Edit
        public ActionResult Edit(int? id)
        {
            mTopic mTopic = new mTopic();
            ViewBag.ListTopic = new SelectList(db.Topic.ToList(), "ID", "Name", 0);
            mPost mPost = db.Post.Find(id);
            if (mPost == null)
            {
                Notification.set_flash("Không tồn tại bài viết!", "warning");
                return RedirectToAction("Index", "Post");
            }
            return View(mPost);
        }
        [CustomAuthorizeAttribute(RoleID = "ADMIN")]
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(mPost mPost)
        {
            mTopic mTopic = new mTopic();
            ViewBag.ListTopic = new SelectList(db.Topic.ToList(), "ID", "Name", 0);
            if (ModelState.IsValid)
            {
                String strSlug = XString.ToAscii(mPost.Title);
                mPost.Slug = strSlug;
                mPost.Type = "post";
                mPost.Updated_at = DateTime.Now;
                mPost.Updated_by = int.Parse(Session["Admin_ID"].ToString());
                var file = Request.Files["Image"];
                if (file != null && file.ContentLength > 0)
                {
                    String filename = strSlug + file.FileName.Substring(file.FileName.LastIndexOf("."));
                    mPost.Image = filename;
                    String Strpath = Path.Combine(Server.MapPath("~/Public/images/post/"), filename);
                    file.SaveAs(Strpath);
                }

                db.Entry(mPost).State = EntityState.Modified;
                db.SaveChanges();
                Notification.set_flash("Đã cập nhật lại bài viết!", "success");
                return RedirectToAction("Index");
            }
            return View(mPost);
        }
        [CustomAuthorizeAttribute(RoleID = "ADMIN")]
        public ActionResult DelTrash(int? id)
        {
            mPost mPost = db.Post.Find(id);
            mPost.Status = 0;

            mPost.Updated_at = DateTime.Now;
            mPost.Updated_by = int.Parse(Session["Admin_ID"].ToString());
            db.Entry(mPost).State = EntityState.Modified;
            db.SaveChanges();
            Notification.set_flash("Đã chuyển vào thùng rác!" + " ID = " + id, "success");
            return RedirectToAction("Index");
        }
        [CustomAuthorizeAttribute(RoleID = "ADMIN")]
        public ActionResult Undo(int? id)
        {
            mPost mPost = db.Post.Find(id);
            mPost.Status = 2;

            mPost.Updated_at = DateTime.Now;
            mPost.Updated_by = int.Parse(Session["Admin_ID"].ToString());
            db.Entry(mPost).State = EntityState.Modified;
            db.SaveChanges();
            Notification.set_flash("Khôi phục thành công!" + " ID = " + id, "success");
            return RedirectToAction("Trash");
        }
        [CustomAuthorizeAttribute(RoleID = "ADMIN")]
        [HttpPost]
        public JsonResult changeStatus(int id)
        {
            mPost mPost = db.Post.Find(id);
            mPost.Status = (mPost.Status == 1) ? 2 : 1;

            mPost.Updated_at = DateTime.Now;
            mPost.Updated_by = int.Parse(Session["Admin_ID"].ToString());
            db.Entry(mPost).State = EntityState.Modified;
            db.SaveChanges();
            return Json(new { Status = mPost.Status });
        }
        [CustomAuthorizeAttribute(RoleID = "ADMIN")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                Notification.set_flash("Không tồn tại bài viết!", "warning");
                return RedirectToAction("Index", "Post");
            }
            mPost mPost = db.Post.Find(id);
            if (mPost == null)
            {
                Notification.set_flash("Không tồn tại bài viết!", "warning");
                return RedirectToAction("Index", "Post");
            }
            return View(mPost);
        }
        [CustomAuthorizeAttribute(RoleID = "ADMIN")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                Notification.set_flash("Không tồn tại bài viết!", "warning");
                return RedirectToAction("Index", "Post");
            }
            mPost mPost = db.Post.Find(id);
            if (mPost == null)
            {
                Notification.set_flash("Không tồn tại bài viết!", "warning");
                return RedirectToAction("Index", "Post");
            }
            return View(mPost);
        }
        [CustomAuthorizeAttribute(RoleID = "ADMIN")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            mPost mPost = db.Post.Find(id);
            db.Post.Remove(mPost);
            db.SaveChanges();
            Notification.set_flash("Đã xóa vĩnh viễn", "danger");
            return RedirectToAction("Trash");
        }

    }
}

SnoopShop/Controllers/ModuleController.cs
using SnoopShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SnoopShop.Controllers
{
    public class ModuleController : Controller
    {
        private SnoopShopDbContext db = new SnoopShopDbContext();
        public ActionResult Categories()
        {
            return View("_Categories", db.Category.Where(m => m.ParentID == 0 && m.Status == 1).ToList());
        }
        public ActionResult SlideShow()
        {
            // Position = 1 = SlideShow
            return View("_SlideShow", db.Slider.Where(m => m.Status == 1 && m.Position == "1").ToList());
        }
        public ActionResult Header()
        {
            ViewBag.Promotion = db.Post.Where(m => m.Status == 1 && m.Type == "post" && m.TopicID == 22).OrderByDescending(m => m.Created_at).Take(3).ToList();
            var list = db.Category.Where(m => m.Status == 1).ToList();
            return View("_Header", list);
        }
        public ActionResult Footer()
        {
            ViewBag.Title = db.Menu.Where(m => m.Status == 1 && m.Positon == "footer" && m.ParentID == 0).Take(2).ToList();
            return View("_Footer", db.Menu.Where(m => m.Status == 1 && m.Positon == "footer").ToList());
        }
        public ActionResult HomeSlideShow()
        {
            ViewBag.Slider = db.Slider.Where(m => m.Status == 1 && m.Position == "2").OrderByDescending(m => m.Created_at).Take(2).ToList();
            return View("_HomeSlideShow", db.Post.Where(m => m.Status == 1 && m.Type == "post" && m.TopicID == 21).ToList());
        }
        public ActionResult Popu()
        {
            return View("_Popu");
        }
        public ActionResult ListCategory()
        {
            var list = db.Category.Where(m => m.Status == 1 && m.ParentID == 0).ToList();
            return View("_ListCategory", list);
        }
        public ActionResult NewsHome()
        {
            return View("_NewsHome", db.Post.Where(m => m.Status == 1 && m.Type == "post").OrderByDescending(m => m.Created_at).Take(5).ToList());
        }
        public ActionResult Login()
        {
            return View("_Login");
        }
        public ActionResult MainMenu()
        {
            return View("_MainMenu", db.Menu.Where(m => m.Status == 1 && m.Positon == "header").ToList());
        }
        // partial page load with ajax
        public ActionResult MiTC()
        {
            return View("_MiTC");
        }
        public ActionResult ICart()
        {
            return View("_ICart");
        }

    }
}

SnoopShop/Views/Site/Contact.cshtml
@{ ViewBag.Title = "Liên hệ";
                Layout = "~/Views/Shared/_LayoutSite.cshtml"; }
@Html.Partial("_Nofit")
<script src="~/Public/js/sweetalert2@9.js"></script>
<div class="container-91 row my-2 mb-5">
    <div class="col-6">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3918.5155168979272!2d106.77462051528423!3d10.848339860827414!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3175270c9cf29ddd%3A0x4ffbbadc39b27d2d!2zNzcgVMOibiBM4bqtcCAxLCBIaeG7h3AgUGjDuiwgUXXhuq1uIDksIEjhu5MgQ2jDrSBNaW5oLCBWaeG7h3QgTmFt!5e0!3m2!1svi!2s!4v1595146283840!5m2!1svi!2s" width="100%" height="780" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
    </div>
    <div class="col-6">
        <div class="ml-2">
            <h2 class="my-4">Liên hệ</h2>
            <div class="my-3">
                <small class="text-secondary">Địa chỉ của chúng tôi</small>
                <strong class="d-block" style="font-size:14px; color:#252a2b">
                    77 Tân Lập 1, P.Tân Phú, Q.9,
                    TP.HCM
                </strong>
            </div>
            <div class="my-3">
                <small class="text-secondary">Email chúng tôi</small>
                <strong class="d-block" style="font-size:14px; color:#252a2b">email@gmail.com</strong>
            </div>
            <div class="my-3">
                <small class="text-secondary">Điện thoại</small>
                <strong class="d-block" style="font-size:14px; color:#252a2b">0123 456 789</strong>
            </div>
            <div class="my-3">
                <small class="text-secondary">Thời gian làm việc</small>
                <strong class="d-block" style="font-size:14px; color:#252a2b">
                    Tất cả các ngày trong tuần, từ 8h30
                    đến 17h30
                </strong>
            </div>


            <h4 class="my-4">Gửi thắc mắc cho chúng tôi</h4>

            <style>
                .form-contact input {
                    padding: 20px;
                    color: #333;
                }

                    .form-contact input::placeholder {
                        padding: 0;
                    }

                .form-contact textarea::placeholder {
                    padding: 0;
                }
            </style>

            <!--form-->
            <form class="form-contact" method="POST" action="Site/SubmitContact">

                <div class="form-group mb-4">
                    <input type="text" name="Fullname" class="form-control rounded-0 py-4 bg-light" aria-describedby="emailHelp" placeholder="Tên của bạn" required="" style="">
                </div>
                <div class="row mb-2 p-0">
                    <div class="form-group col-6">
                        <input type="email" name="Email" class="form-control rounded-0 py-4 bg-light" placeholder="Email của bạn" required="">
                    </div>
                    <div class="form-group col-6">
                        <input type="text" name="Phone" class="form-control rounded-0 py-4 bg-light" placeholder="Số điện thoại của bạn" required="" pattern="[0-9]{10,12}">
                    </div>
                </div>
                <div class="form-group mb-4">
                    <input type="text" name="Title" class="form-control rounded-0 py-4 bg-light" placeholder="Tiêu đề" required="">
                </div>
                <div class="form-group">
                    <textarea name="Detail" class="form-control rounded-0 bg-light pl-3" id="" rows="4" placeholder="Nội dung" required=""></textarea>
                </div>

                <button type="submit" class="btn btn-dark rounded-0 py-2 px-4 ">
                    <small>
                        GỬI CHO CHÚNG TÔI
                    </small>
                </button>
            </form>
        </div>
    </div>
</div>

SnoopShop/Views/Site/Home.cshtml
@model IEnumerable<SnoopShop.Models.mCategory>
@{ ViewBag.Title = "SnoopShop";
                Layout = "~/Views/Shared/_LayoutSite.cshtml"; }

<div class="home-slider bg-" style="background:#f3f3f3">
    @Html.Action("HomeSlideShow", "Module")
</div>

<div class="promo-so">
    <div>
        <img src="~/Public/images/sliders/title.png" alt="" class="d-block  m-auto pb-2">
    </div>
    <div class="container-91 taiche">
        <div id="owl-wrap" class="owl-carousel owl-theme">

            @foreach (var p in ViewBag.PromotionProduct)
            {
<div class="p-item">
    <a href="@p.Slug">
        <div class="p-img">
            @if (p.Installment == 1)
            {
<div class="anw">Trả góp <span class="font-weight-bold">0%</span></div>}
            <img src="~/Public/images/products/@p.Image" alt="" class="beau">
        </div>
        <div class="couple">
            @if (p.Discount == 1)
            {
<img src="~/Public/images/online-giảm-sốc-1x.png" alt="" class="h-100">}
        </div>
        <div class="p-np">
            @p.Name
        </div>
        <div class="p-price">
            <div class="price">
                @String.Format("{0:0,0₫}", p.ProPrice)
            </div>
            <div class="old-price float-left">
                @String.Format("{0:0,0₫}", p.Price)
            </div>
            <div class="khongbietdattenlagi float-left"> (-@String.Format("{0:0}", ((p.Price - p.ProPrice) / p.Price * 100))%)</div>
        </div>
    </a>
</div>            }
        </div>
    </div>
</div>


<div class="promo-so">
    <div class="container-91 h4 text-center font-weight-bold mb-2" style="color:#d0021b;">
        SẢN PHẨM MỚI
    </div>
    <div class="container-91 taiche">
        <div id="new-product" class="owl-carousel owl-theme">

            @foreach (var p in ViewBag.NewProduct)
            {
<div class="p-item">
    <a href="@p.Slug">
        <div class="p-img">
            @if (p.Installment == 1)
            {
<div class="anw">Trả góp <span class="font-weight-bold">0%</span></div>}
            <img src="~/Public/images/products/@p.Image" alt="" class="beau">
        </div>
        <div class="couple">
            @if (p.Discount == 1)
            {
<img src="~/Public/images/online-giảm-sốc-1x.png" alt="" class="h-100">}
        </div>
        <div class="p-np">
            @p.Name
        </div>
        <div class="p-price">
            <div class="price">
                @String.Format("{0:0,0₫}", p.ProPrice)
            </div>
            <div class="old-price float-left">
                @String.Format("{0:0,0₫}", p.Price)
            </div>
            <div class="khongbietdattenlagi float-left"> (-@String.Format("{0:0}", ((p.Price - p.ProPrice) / p.Price * 100))%)</div>
        </div>
    </a>
</div>            }
        </div>
    </div>
</div>
<div class="tab-products">
    <div class="container-91">
        <div class="title">Sản phẩm theo danh mục</div>
        <div class="tab-tab-tab">

            <ul class="nav nav-pills" id="pills-tab" role="tablist">
                @{ var i = 0;}
                @foreach (var cat in Model)
                {
    <li class="nav-item" role="presentation">
        <a class="nav-link @(i == 0 ? "active" : "")" id="tab-tab-@cat.ID" data-toggle="pill" href="#tab-@cat.ID" role="tab" aria-controls="tab-tab-tab-@cat.ID" aria-selected="true">@cat.Name</a>
    </li>i++;
                }
            </ul>

            <div class="tab-content" id="pills-tabContent">
                @{ i = 0;}
                @foreach (var cat in Model)
                {
    <div class="tab-pane fade show @(i == 0 ? "active" : "") " id="tab-@cat.ID" role="tabpanel" aria-labelledby="tab-tab-@cat.ID">
        @Html.Action("ProductHome", "Site", new { catid = cat.ID })
    </div>i++;
                }
            </div>
        </div>
    </div>
</div>
<div class="py-3" style="background:#f3f3f3">
    <div class="container-91">
        <a href=""><img src="images/sliders/stickert5-03-394x75.png" alt="" width="406"></a>
        <a href=""><img src="images/sliders/stickert5-03-394x75.png" alt="" width="406"></a>
        <a href=""><img src="images/sliders/stickert5-03-394x75.png" alt="" width="406"></a>
    </div>
</div>
<div class="news-home" style="background:#f3f3f3">
    @Html.Action("NewsHome", "Module")
</div>
@Html.Action("Popu", "Module")

SnoopShop/Views/Site/Other.cshtml
@{ ViewBag.Title = "Other";
                Layout = "~/Views/Shared/_LayoutSite.cshtml"; }

<h2>Other</h2>

SnoopShop/Views/Site/PostPage.cshtml
@model SnoopShop.Models.mPost
@{ ViewBag.MetaDesc = Model.MetaDesc;
                ViewBag.MetaKey = Model.MetaKey;
                ViewBag.Title = Model.Title;
                Layout = "~/Views/Shared/_LayoutSite.cshtml"; }
<div class="container-91">
    <div class="h3 my-3">
        @Model.Title
    </div>

    @Html.Raw(Model.Detail)
</div>

SnoopShop/Views/Site/ProductCategory.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<SnoopShop.Models.mProduct>
@{ ViewBag.Title = ViewBag.CatName;
                Layout = "~/Views/Shared/_LayoutSite.cshtml"; }

<div class="" style="background:#f3f3f3">
    <div class="breadcrumb-c clearfix d-block pl-2">
        <ul class="container-91">
            <li><a href="~/">Trang chủ </a></li>
            <li class="dsfsd"><a href="~/@ViewBag.Slug"> @ViewBag.CatName</a></li>
        </ul>
    </div>

    <div class="container-91 py-1" style="background: #f3f3f3">
        <div class="row">
            <div class="col-3 w-100">
                @Html.Action("ListCategory", "Module")
            </div>
            <div class="col-9" style="margin-left:-20px; margin-right:20px;">
                <div class="text-left pl-3 py-3 border bg-white rounded-top">
                    <div class="h5 font-weight-bold d-inline">@ViewBag.CatName </div>
                    <div class="d-inline text-secondary">(@ViewBag.CountingTheProduct sản phẩm)</div>
                </div>
                <div class="mt-1 pl-3 py- border border-bottom-0 bg-white rounded-top">
                    <div class="row">
                        <div class="col-8"></div>
                        <div class="col-2">
                            <select class="form-control form-control-sm my-2" style="height:27px;font-size:12px;">
                                <option>Bán chạy nhất</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                                <option>5</option>
                            </select>
                        </div>
                        <div class="col-2">
                            <div class="text-right">
                                <button class="btn grid"><i class="grid-icon-active i"></i> </button>
                                <button class="btn list"><i class="list-icon i"></i> </button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="product-category border border-right-0 border">
                    @if (Model.Count() == 0)
                    {
        <div class="text-center text-danger mt-5"> Danh mục chưa có sản phẩm</div> }
                    else
                    {
                        foreach (var row in Model)
                        {
        <div class="nghiep-item item border-right border-bottom">
            <a href="~/@row.Slug">
                <div class="t-img">
                    <img src="~/Public/images/products/@row.Image" alt="" class="beau">
                    @if (row.Installment == 1)
                    {
<div class="anw">Trả góp <span class="font-weight-bold">0%</span></div>}

                </div>
                <div class="g">
                    <div class="couple">
                        @if (row.Installment == 1)
                        {
    <div class="anw">Trả góp <span class="font-weight-bold">0%</span></div>
                            <div class="giam">Giảm 200,000đ</div>}
                        @if (row.Discount == 1)
                        {
    <img src="~/Public/images/online-giam-soc.png" class="h-100" />}
                    </div>
                    <div class="t-np">
                        @row.Name
                    </div>
                    <div class="t-price">
                        <div class="price">
                            @String.Format("{0:0,0₫}", row.ProPrice)
                        </div>
                        <div class="old-price float-left">
                            @String.Format("{0:0,0₫}", row.ProPrice)
                        </div>
                        <small class="khongbietdattenlagi float-left text-danger">&nbsp; (-@String.Format("{0:0}", ((row.Price - row.ProPrice) / row.Price * 100))%)</small>
                    </div>
                    <img src="~/Public/images/online-giam-soc.png" class="onlinegiamsoc" />
                </div>
            </a>
        </div>}
                    }
                </div>
            </div>
        </div>
        <div class="pagination-91 my-3">
            @Html.PagedListPager(Model, page => Url.Action("Index", "Site", new { slug = ViewBag.Slug, page }))
        </div>
    </div>
    <div style="clear:both"></div>
</div>